### ISSUE TITLE
Remove only pmm dangling images

### ISSUE THREAD

**Issue by boutetnico** [boutetnico/ansible-role-percona-pmm-server#7]
Waiting for PMM to add labels on their image so I can filter them:

```
- name: Remove dangling docker image
  docker_prune:
    images: true
    images_filters:
      dangling: true
      label: "name={{ pmm_server_docker_image_name }}"
```

https://jira.percona.com/browse/PMM-7552
